FROM node:8

WORKDIR /opt/monerod_exporter

RUN git clone https://github.com/ExcitableAardvark/monerod_exporter.git --branch=master --depth=1 .

RUN npm install

EXPOSE 8080

ENTRYPOINT ["node", "index.js"]
