{
 "title": "Node Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Peer Map",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 0 },
   "targets": [
    { "expr": "geoip{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peer Counts",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(geoip{status=\"gray\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(geoip{status=\"white\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mainnet",
   "type": "stat",
   "description": "Whether the node is running against mainnet or not.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_mainnet", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "Synchronized",
   "type": "stat",
   "description": "Whether the node is fully in sync with the network or not.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_synchronized", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "For how long this node has been up.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monero_info_uptime_seconds_total",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size of node's database on disk.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monero_info_database_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Amount of free space in the partition where the node's database is located at.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_free_space_bytes", "legendFormat": "free space" }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "stat",
   "description": "Total amount of data sent and received by this node.",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    { "expr": "monero_net_rx_bytes", "legendFormat": "in" },
    { "expr": "monero_net_tx_bytes", "legendFormat": "out" }
   ]
  },
  {
   "title": "Height and Target",
   "type": "stat",
   "description": "Current chain's block height vs node's current height. When syncing, let's one quickly tell how far the node is from being synchronized with the network.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "monero_info_height", "legendFormat": "height" },
    { "expr": "monero_info_target_height > 0", "legendFormat": "target" }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "description": "Node's current height",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "monero_info_height", "legendFormat": "height" },
    { "expr": "monero_info_target_height > 0", "legendFormat": "target" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "For how long this node has been up.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "monero_info_uptime_seconds_total",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "description": "Size of node's database on disk.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monero_info_database_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Connected Peers' Height",
   "type": "timeseries",
   "description": "The distribution of the heights of our peers\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "monero_p2p_connections_height{quantile=~\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Total amount of data sent and received by this node.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monero_net_rx_bytes", "legendFormat": "in" },
    { "expr": "monero_net_tx_bytes", "legendFormat": "out" }
   ]
  },
  {
   "title": "Free space",
   "type": "timeseries",
   "description": "Amount of free space in the partition where the node's database is located at.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monero_info_free_space_bytes", "legendFormat": "free space" }
   ]
  },
  {
   "title": "P2P Peers Data In Rate",
   "type": "timeseries",
   "description": "The distribution of data retrieval from our connected peers.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "monero_p2p_connections_rx_rate_bps{quantile=\"1\"}",
     "legendFormat": "quantile 1"
    }
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "description": "Rate of data transmission in and out from this node (p2p and rpc).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(monero_net_rx_bytes[$__interval])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(monero_net_tx_bytes[$__interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "P2P Peers Data Out Rate",
   "type": "timeseries",
   "description": "The distribution of data transmission to our connected peers.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "monero_p2p_connections_tx_rate_bps{quantile=\"1\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Time spent serving RPC methods",
   "type": "timeseries",
   "description": "Average amount of time spent serving RPC methods over that past minute.\n\nps.: this includes the calls made by the stats collector too.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(monero_rpc_seconds_total[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC hits per Interval",
   "type": "timeseries",
   "description": "Average number of RPC requests served over the past interval.\n\nps.: this includes the calls made by the stats collector too.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(monero_rpc_hits_total[1m])",
     "legendFormat": "{{method}} {{ $__interval }}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (2m)",
   "type": "timeseries",
   "description": "Number of transactions in the transaction pool (mempool).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_transactions",
     "legendFormat": "mempool tx"
    }
   ]
  },
  {
   "title": "Mempool Bytes",
   "type": "timeseries",
   "description": "Total size of the transaction pool (mempool)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Mempool Fees (2m)",
   "type": "timeseries",
   "description": "Total amount of fees for the transactions in the transaction pool.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ɱ" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_fees_monero",
     "legendFormat": "fee"
    }
   ]
  },
  {
   "title": "Mining Difficulty",
   "type": "timeseries",
   "description": "Difficulty used for mining the last block",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "monero_lastblock_difficulty", "legendFormat": "size" }
   ]
  },
  {
   "title": "Mining Rewards",
   "type": "timeseries",
   "description": "Total block rewards granted to the miner of this block (transaction fees + block subsidy).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ɱ" } },
   "targets": [
    { "expr": "monero_lastblock_reward_monero", "legendFormat": "total rewards" }
   ]
  },
  {
   "title": "Inputs and Outputs",
   "type": "timeseries",
   "description": "Sum of inputs and outputs used in the last block's transactions.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "monero_lastblock_transactions_inputs_sum",
     "legendFormat": "inputs"
    },
    {
     "expr": "monero_lastblock_transactions_outputs_sum",
     "legendFormat": "outputs"
    }
   ]
  },
  {
   "title": "Peerlists' count",
   "type": "timeseries",
   "description": "Number of peers in each peer list.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "monero_peerlist", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Weird cases",
   "type": "timeseries",
   "description": "A couple of statistics that reveals weird scenarios found in the transaction pool.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_double_spends > 0",
     "legendFormat": "double spends"
    },
    {
     "expr": "monero_transaction_pool_older_than_10m > 0",
     "legendFormat": "older than 10m"
    },
    {
     "expr": "monero_transaction_pool_failing_transactions > 0",
     "legendFormat": "failing transactions"
    },
    {
     "expr": "monero_transaction_pool_not_relayed > 0",
     "legendFormat": "not relayed"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "description": "Total size of the block",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monero_lastblock_size_bytes", "legendFormat": "size" }
   ]
  },
  {
   "title": "RPC Connections",
   "type": "timeseries",
   "description": "Number of RPC connections being served.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "monero_info_rpc_connections", "legendFormat": "connections" }
   ]
  },
  {
   "title": "Connections' Age",
   "type": "timeseries",
   "description": "The distribution of the age of the connections established to/from our nodes.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(monero_p2p_connections_age{quantile=\"1\"})",
     "legendFormat": "quantile 1"
    }
   ]
  },
  {
   "title": "Connections by connection state",
   "type": "timeseries",
   "description": "Number of connections based on their connection state.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(monero_p2p_connections) by (state)",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}