{
 "title": "Daemon Stats",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(monerod_connections_incoming)",
     "legendFormat": "Incoming"
    },
    {
     "expr": "avg(monerod_connections_outgoing)",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "avg(monerod_rpc_connections_count)",
     "legendFormat": "RPC"
    }
   ]
  },
  {
   "title": "Block Reward (XMR)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(monerod_block_reward)", "legendFormat": "Block Reward (XMR)" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(monerod_tx_mempool)", "legendFormat": "Pool Transactions" }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "avg(monerod_block_difficulty)" }
   ]
  },
  {
   "title": "Chain Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "monerod_database_size", "legendFormat": "Chain Size" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(monerod_tx_chain)" }
   ]
  }
 ]
}