global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: node-exporter
scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["exporter:9000"]
