name: Publish images to Docker Hub

on:
  push:
    branches: master

env:
  DH_USER: lalanza808

jobs:
  publish_images:
    runs-on: ubuntu-latest
    name: Publish selected Docker image to Dockerhub
    if: contains(github.event.head_commit.message, 'release(')
    steps:
      - name: Authenticate to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push new nodemapper image
        if: contains(github.event.head_commit.message, 'release(nodemapper)')
        run: bash release.sh nodemapper ${{ env.DH_USER }}

      - name: Build and push new monero image
        if: contains(github.event.head_commit.message, 'release(monero)')
        run: bash release.sh monero ${{ env.DH_USER }}

      - name: Build and push new exporter image
        if: contains(github.event.head_commit.message, 'release(exporter)')
        run: bash release.sh exporter ${{ env.DH_USER }}

      - name: Build and push new tor image
        if: contains(github.event.head_commit.message, 'release(tor)')
        run: bash release.sh tor ${{ env.DH_USER }}

      - name: Build and push new i2p image
        if: contains(github.event.head_commit.message, 'release(i2p)')
        run: bash release.sh i2p ${{ env.DH_USER }}
